# Generated by Django 3.2.6 on 2021-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20210719_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='googleId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
