# Generated by Django 3.2.6 on 2021-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_user_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='googleId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
