# Generated by Django 3.2.6 on 2021-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_user_googleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socialId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='socialType',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
