# Generated by Django 3.2.6 on 2021-09-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_auto_20210924_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='googleId',
        ),
    ]
