# Generated by Django 3.2.6 on 2021-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='VerificationId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
